### ISSUE TITLE
连接后手机界面无法显示

### ISSUE THREAD

**Issue by lyl0921** [barry-ran/QtScrcpy#188] opened 2020-05-29 05:47 UTC
连接后手机界面无法显示，但是侧边栏可以操作
报错如下

本软件完全开源免费，严禁用于非法用途，否则后果自负，你可以在下面地址下载:

"QtScrcpy 1.3.5 <https://github.com/barry-ran/QtScrcpy>"

update devices...
adb path: D:/Programs/QtScrcpy/QtScrcpy-win-x64-v1.3.5/adb

adb run
AdbProcess::out:List of devices attached
9d69ca24	device

start server...
getScreenRect is empty

AdbProcess::out:D:/Programs/QtScrcpy/QtScrcpy-win-x64-v1.3.5/scrcpy-server: 1 file pushed. 0.3 MB/s (26142 bytes in 0.086s)

server start finish in 3.271s

AdbProcess::out:[server] WARN: Max FPS is only supported since Android 10, the option has been ignored

QOpenGLShader::compile(Fragment): ERROR: 0:2: '' : No precision specified for (float)
ERROR: 0:8: '' : No precision specified for (float)
ERROR: 0:9: '' : No precision specified for (float)
ERROR: 0:13: '' : No precision specified for (float)
ERROR: 0:14: '' : No precision specified for (float)
ERROR: 0:15: '' : No precision specified for (float)

*** Problematic Fragment shader source code ***
#ifdef GL_KHR_blend_equation_advanced
#extension GL_ARB_fragment_coord_conventions : enable
#extension GL_KHR_blend_equation_advanced : enable
#endif
#line 1

    varying vec2 textureOut;        // ???????????????
    uniform sampler2D textureY;     // uniform ???????????????????
    uniform sampler2D textureU;     // sampler2D?2D???
    uniform sampler2D textureV;     // ??yuv??????
    void main(void)
    {
        vec3 yuv;
        vec3 rgb;

        // SDL2 BT709_SHADER_CONSTANTS
        // https://github.com/spurious/SDL-mirror/blob/4ddd4c445aa059bb127e101b74a8c5b59257fbe2/src/render/opengl/SDL_shaders_gl.c#L102
        const vec3 Rcoeff = vec3(1.1644,  0.000,  1.7927);
        const vec3 Gcoeff = vec3(1.1644, -0.2132, -0.5329);
        const vec3 Bcoeff = vec3(1.1644,  2.1124,  0.000);

        // ???????textureY???textureOut???
        yuv.x = texture2D(textureY, textureOut).r;
        yuv.y = texture2D(textureU, textureOut).r - 0.5;
        yuv.z = texture2D(textureV, textureOut).r - 0.5;

        // ?????rgb
        // ??????
        yuv.x = yuv.x - 0.0625;
        rgb.r = dot(yuv, Rcoeff);
        rgb.g = dot(yuv, Gcoeff);
        rgb.b = dot(yuv, Bcoeff);
        // ?????
        gl_FragColor = vec4(rgb, 1.0);
    }

***

QOpenGLShaderProgram::attributeLocation(vertexIn): shader program is not linked

QOpenGLShaderProgram::attributeLocation(vertexIn): shader program is not linked

QOpenGLShaderProgram::attributeLocation(textureIn): shader program is not linked

QOpenGLShaderProgram::attributeLocation(textureIn): shader program is not linked

QOpenGLShaderProgram::uniformLocation(textureY): shader program is not linked

QOpenGLShaderProgram::uniformLocation(textureU): shader program is not linked

QOpenGLShaderProgram::uniformLocation(textureV): shader program is not linked

是对硬件有什么要求，还是需要额外安装其他什么东西。

**Comment by barry-ran** [comment] 2020-06-06 11:27
Duplicate of #129

**Closed by barry-ran** 2020-06-06 11:27 UTC
