### ISSUE TITLE
鼠标无法控制。

### ISSUE THREAD

**Issue by billhong** [barry-ran/QtScrcpy#212] opened 2020-06-10 09:17 UTC
小米NOTE3.
屏幕能共享，下拉通知、关闭屏幕等有效，音量调节、菜单项目无效。也就是部分有效部分无效。
手机操作能够实时电脑同步。

**Comment by billhong** [comment] 2020-06-10 09:20
stop server

start server...
getScreenRect is empty

Script updated.

AdbProcess::out:D:/Program Files/QtScrcpy-win-x64-v1.3.6/scrcpy-server: 1 file pushed. 1.3 MB/s (26142 bytes in 0.020s)

server start finish in 1.394s

AdbProcess::error:java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:231)
	at java.io.FileInputStream.<init>(FileInputStream.java:165)
	at java.io.FileInputStream.<init>(FileInputStream.java:112)
	at java.io.FileReader.<init>(FileReader.java:58)
	at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
	at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
	at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
	at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
	at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
	at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
	at android.content.res.Resources.<init>(Resources.java:267)
	at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
	at android.content.res.Resources.getSystem(Resources.java:190)
	at android.app.LoadedApk.<init>(LoadedApk.java:211)
	at android.app.ContextImpl.createSystemContext(ContextImpl.java:2331)
	at android.app.ActivityThread.getSystemContext(ActivityThread.java:2168)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:56)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	at com.genymobile.scrcpy.Server.main(Server.java:163)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:388)

AdbProcess::out:[server] WARN: Max FPS is only supported since Android 10, the option has been ignored

**Comment by barry-ran** [comment] 2020-06-12 02:32
Duplicate of #76

**Closed by barry-ran** 2020-06-12 02:32 UTC
